#pragma once

#include <ntddk.h>

#define STATUS_DEFINER_CUSTOMER	0x1
#define STATUS_FACILITY_MY_EDR	0x1FFF

#define STATUS_CUSTOMER_DEFINED(severity, facility, code)	NTSTATUS((severity << 30) + ((STATUS_DEFINER_CUSTOMER << 29) + (facility << 16) + code))

#define STATUS_MY_EDR(severity, code)		STATUS_CUSTOMER_DEFINED(severity, STATUS_FACILITY_MY_EDR, code)
#define STATUS_MY_EDR_SUCCESS(code)			STATUS_MY_EDR(STATUS_SEVERITY_SUCCESS, code)
#define STATUS_MY_EDR_INFORMATIONAL(code)	STATUS_MY_EDR(STATUS_SEVERITY_INFORMATIONAL, code)
#define STATUS_MY_EDR_WARNING(code)			STATUS_MY_EDR(STATUS_SEVERITY_WARNING, code)
#define STATUS_MY_EDR_ERROR(code)			STATUS_MY_EDR(STATUS_SEVERITY_ERROR, code)

#define STATUS_MY_EDR_QUEUE_IS_EMPTY					STATUS_MY_EDR_ERROR(0x0001)
#define STATUS_MY_EDR_QUEUE_IS_FULL						STATUS_MY_EDR_ERROR(0x0002)

#define STATUS_MY_EDR_AVL_TABLE_INSERT_ELEMENT_FAILED	STATUS_MY_EDR_ERROR(0x0003)
#define STATUS_MY_EDR_AVL_TABLE_ELEMENT_WAS_NOT_FOUND	STATUS_MY_EDR_ERROR(0x0004)
#define STATUS_MY_EDR_AVL_TABLE_DELETE_ELEMENT_FAILED	STATUS_MY_EDR_ERROR(0x0005)
